FROM mcr.microsoft.com/devcontainers/base:ubuntu26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    ghdl \
    make \
    build-essential \
    git \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV GHDL_PREFIX=/usr/local/lib/ghdl